language: go
go:
- 1.5
branches:
 only:
 - master
env:
  global:
  - secure: C5qMaora+l1JkWeq5+L1Lj2kit9ZOFUi7obIHixM73DzPq/8POJHTXM3EaE+IDm58B41LhlzxkpD0EsQGuA9x8Sr0z/UMZ34EhrIa60ZbZNIvI0sTEpPnu5BW+B01ICPpFDDzl9ZmgHLLnX+Von2HMld1NDrYWLS7GIyUapuKwF0oQRXo3vHaGj21CPYIS4wI6HUx1zzoohqKD6/V5vbkNdZKgd8XJC5rTFrSJBYmweoip1/FRzJHnyzOlJGiM/llUqZ1RoVDindXhCBDxaqHLC7OOBhPEMua3SQEwPqe7Vz+4GQCyGqX5kIL4fFaXFM7G7MEdjaqahXq0lRFyiXzG5PSW6NstGZ6EKlE6GgD1RJY5TvTU9rvAChDf2j2lwLTYAiRqmBcnjMsfiQF55AMGgXeEo6Ln760z8GV8aKerQ0y+2hh49RtH62T08uLAUYg0K+kYT9eiPvBYlenT/o/Uicc6MVlHWhsgZJn2cz3fWvyydWazgiwxfjDPu0c58eaVwpdGOy7EEll/uU5CS5w4ohsltEQZdAGPjMJb1Ey3Cnoxos9P/Iy/Bb7j0b7vqgJxqm9FlWJZauLNWbHL3qKpdHWiE84Zl0XXV8eYkiVwIAXimwqgKbIMcEXTf8QJDqiyUUQeVeUDK436psmKVrFDT1azfx03iiR9Ye1hK46ig=
after_script:
- go get -v github.com/laher/goxc
- goxc -wlc default publish-github -apikey=$GHRA
- goxc
